### PR TITLE
 Make automated tests run only for non-draft PRs

### PR DESCRIPTION
**Pull request by ben18785**

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Still running the tests. But... could be because the files in master ask us to?

**Comment by ben18785** [comment]
@MichaelClerx Before I hit, "Ready for review" nothing ran. Only when I clicked this did it start.

**Comment by MichaelClerx** [comment]
Interesting!

Feel free to temporarily disable the PR merging rules while you play with this one :D

**Comment by MichaelClerx** [comment]
It seems they're still not running. Does it need a post-draft commit for them to run?

**Comment by ben18785** [comment]
Hmm, now that I've removed ``review_requested`` it doesn't seem to trigger it... I removed this because I thought we'd want to allow tests to run before we'd assigned a reviewer (but after we'd converted it from a draft PR to a full one)..

**Comment by ben18785** [comment]
This seems to now work. It triggers the tests once a PR is made a non-draft.

**Review by MichaelClerx — APPROVED** [review]

**Pull request merged**
