### PR TITLE
Nested MCMC

### PR DESCRIPTION
**Pull request by MichaelClerx**

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Hi @ben18785 ! This seems to overlap largely with the refactoring branch, but also has some recent commits?

**Comment by ben18785** [comment]
@MichaelClerx This is another nested method method called nested MCMC. Have updated title.

**Comment by ben18785** [comment]
@MichaelClerx note nested MCMC is a type of nested sampler.

**Comment by MichaelClerx** [comment]
Ok! We might want to rebase it then at some point after we've merged nested sampler refactoring? Seems to contain a lot of the same commits

**Comment by MichaelClerx** [comment]
Have fixed the mess I made of this branch with `git`. Please delete your local copy and re-checkout the branch before continuing work on this.

**Comment by MichaelClerx** [comment]
Hey @ben18785 , I guess this will need to be re-implemented on top of the refactored nested samplers? It's currently built on an old nested-refactoring branch, which we discarded in favour of a newer version you did

**Comment by ben18785** [comment]
Yep, it can be closed for now.

**Comment by MichaelClerx** [comment]
Cool! Shall I keep the branch so you can look at the code if needed?

**Comment by ben18785** [comment]
Yep, thanks.

**Pull request closed without merging**
