### PR TITLE
Update stan interface to pystan 3

### PR DESCRIPTION
**Pull request by MichaelClerx**
See #1333 

- [x] Update setup.py to install new version
- [x] Update tests to skip pystan on Python 3.6
- [x] Update PINTS code to pystan 3+
- [x] Update example notebook

### CODE REVIEW

**Comment by MichaelClerx** [comment]
@ben18785 I've made this PR that has the infrastructure bits sorted out for #1333:

- The tests on Python 3.6 do not install pystan. This is detected by the unit tests, so that the stan-related tests are skipped and the unit tests pass on Python 3.6 (notice skipped=3 at the bottom)
- On Python 3.7 and higher, pystan is installed, so that the unit tests are run. Because these expect pystan 2 but we've installed pystan 3 the tests fail

So all ready to adapt to the new interface!

**Comment by MichaelClerx** [comment]
Hey @ben18785 . I think this might be it? No idea what I'm doing but the tests pass.

Things that are gone in this implementation:
```
            refresh=0,
            control={'adapt_engaged': False})
```
but this is because the entire "fit" operation is skipped now

**Review by ben18785 — APPROVED** [review]
Thanks amillion @MichaelClerx -- it all looks good to me. The one thing I have changed is the example notebook as this was using the old interfacing. I wasn't able to check that this ran though as I am having some trouble getting pystan to install on my machine, so would you be able to check it runs for you? After that happy to merge.

**Comment by ben18785** [comment]
Ah ha. Is it because ``get_param_names`` returns a list of length 3 (where one of them is a nested list)? Do we need to flatten this list?

**Comment by MichaelClerx** [comment]
That sounds correct!
Do you want to write & commit a test for this issue first?

(Solution is probaly this:
```
from itertools import chain
list(chain.from_iterable([[180.0], [173.8], [164.2], [156.5], [147.2], [138.2]]))
```)

**Comment by MichaelClerx** [comment]
Hey @ben18785 do you know what's happening here?

With the 8 schools example you gave the current code thinks there's 18 parameters (2*8+1)

**Comment by ben18785** [comment]
The issue is the "transformed parameters" block in this example. The PyStan interface doesn't differentiate between parameters defined in the "parameters" block vs those defined in the "transformed parameters" block. Whereas, PINTS only needs parameters defined in the "parameters" block...

It may be possible that something like this could work based on regex: https://github.com/arviz-devs/arviz/blob/5af74712950c99d486cc0f62db66537670e3bfcc/arviz/data/base.py#L444 but this seems a bit messy!

**Comment by MichaelClerx** [comment]
@ben18785 any way to filter out the transformed parameters?
```
Posterior
================================================================================
constrain_pars
constrained_param_names
data
dims
fixed_param
grad_log_prob
hmc_nuts_diag_e_adapt
log_prob
model_name
param_names
program_code
random_seed
sample
unconstrain_pars

Module
================================================================================
constrained_param_names
fixed_param_wrapper
get_dims
get_param_names
hmc_nuts_diag_e_adapt_wrapper
log_prob
log_prob_grad
model_name
transform_inits
write_array
```

**Comment by MichaelClerx** [comment]
None of those methods seem to help in this case. Hmmm!
I would prefer putting in a request with pystan to add some method that gives us the info we need, instead of trying to parse the stan model code. I think we could hack something together in 15 minutes that would acceptably parse it for our purposes, but then we'd forever be finding small bugs and new cases we hadn't considered, and basically would end up building a stan parser, when a perfectly good stan parser is already available

**Comment by ben18785** [comment]
Thanks @MichaelClerx -- yes, I think that you're right. I suspect the only thing we can do is to allow the user to set the number of parameters. The one thing, as you say, is the order: need to check if this matches the declaration order (or say alphabetical order).

Alternatively, we could just say that we don't handle Stan models which have a transformed parameters block...everything else works fine I think.

**Comment by MichaelClerx** [comment]
Looking in the code I saw quite a few "in the order they were declared". Will do a quick test and then it's fine, I guess :D

**Comment by MichaelClerx** [comment]
Yeah declared order

**Comment by ben18785** [comment]
Cool -- thanks. So I guess, we just pass this onto the user: they have to
ensure the parameters are passed in the order they are declared in the
"parameters" block. (And they have to say how many parameters there are.)

**Comment by MichaelClerx** [comment]
Do we make the user say there are "1+1+8=10" parameters? Or do we let them say "3"?

**Comment by ben18785** [comment]
10 since PINTS doesn't care whether a parameter is a scalar or an element
of a vector...

**Comment by MichaelClerx** [comment]
Alright @ben18785 , what do you think?

**Comment by ben18785** [comment]
Ha, you went and got the parameter counts! Nice one :) A quick question: how does

`len(code.split(';')) - 1`

deal with vector parameters? Doesn't this just count the total number of things (some of which may be vectors) which are declared?

**Comment by MichaelClerx** [comment]
Yeah exactly. I'm assuming each declaration is a scalar or vector variable. The total "flat" variable count depends on the data, so can't be inferred form the code.

...which, come to think of it, means we need to decide what happens if the data changes. Do we

1. Remove `update_data()`. This is the easiest solution, and not necessarily unfriendly to the user, as models are cached by httpstan
2. Check if n_parameters has changed after a call to `update_data()`, and raise an error if so
3. Check if it has changed, and start reporting a different `n_parameters()`. I'm expecting LogPDFs to have a constant param count in their lifetime, but not sure we have made this official?

**Comment by ben18785** [comment]
@MichaelClerx thanks. Good points. I honestly don't see the point of `update_data` now, since, as you say, models are cached. It was useful previously as it would save us having to re-compile needlessly, but now, I vote for removing it.

**Pull request merged**
