### PR TITLE
Autoregressive-moving-average(1, 1) log-likelihoods

### PR DESCRIPTION
**Pull request by ben18785**
@martinjrobins Built tests for your log-likelihood class and also added ARMA(1,1) log-likelihood. Also, added example notebook showing how assuming independent errors is a bad thing if your errors have these kind of persistences.

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Whenever you add any class (or stand-alone function), please remember to update the documentation in [docs](https://github.com/pints-team/pints/tree/master/docs/source) !

**Comment by MichaelClerx** [comment]
@martinjrobins bit too quick there, these still need to be added to the docs!

**Comment by MichaelClerx** [comment]
(I don't know if there's any way we can have an automated test for that)

**Comment by martinjrobins** [comment]
sorry, forgot about that. I'll add it to the original issue

**Pull request merged**
