### PR TITLE
ABC-SMC

### PR DESCRIPTION
**Pull request by jarthur36**

### CODE REVIEW

**Comment by ben18785** [comment]
@jarthur36 Thanks. I've sorted the flake8 issues -- can you have a look at the other stuff that is causing the tests to fail?

**Comment by MichaelClerx** [comment]
@jarthur36 is there a ticket we can relate this PR too?

**Comment by MichaelClerx** [comment]
Anyone know what the status of this is? @ben18785 ?

**Comment by phumtutum** [comment]
Closing as this was added in https://github.com/pints-team/pints/pull/1442 .

**Pull request closed without merging**
