### PR TITLE
Ellipsoidal now running >10x faster for the logistic example

### PR DESCRIPTION
**Pull request by ben18785**
(with 4x the number of active points and so really ~ 30x faster)!

The method for calculating the bounding ellipse is, however, a bit more approximate. So what I wonder is -- is it worth having both methods in there that a user can choose from? My reasons for doing so are that, for some problems, the improvement in accuracy of the bounding box may be necessary.

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Sounds like a great improvement!

(Implementation wise, If you want to make the new method optional, you could either have an `if` somewhere that decides which method, but you could also have a shared reference to a function that you change, so self._f = self._fast_function or self._f = self._slow_function, and then just call self._f everywhere without needing another if, whatever's easiest!)

**Comment by MichaelClerx** [comment]
Then again, it doubles the amount of testing and maintenance, so only add the option if you know it's necessary!

**Comment by martinjrobins** [comment]
How would selecting between the two methods be for the user?
There seems to me to be two options:
- introducing a hyper-parameter to swap between the two methods
- Having the two methods as two separate classes, sharing a base class for the code common to both.

The latter might be more appropriate if the methods have differing numerical properties.

**Comment by ben18785** [comment]
@MichaelClerx Yep, can we merge this and then create a ticket for me to add an optional fast vs accurate (defaulting to fast, I think) method selection for the user. @martinjrobins I'd prefer to keep these as a single method as it's a bit clunky to have nested and nested_fast etc.

**Comment by MichaelClerx** [comment]
Ok with you @martinjrobins ?

**Comment by ben18785** [comment]
Now addressed in a separate PR.

**Pull request closed without merging**
