### PR TITLE
i1074 gh actions

### PR DESCRIPTION
**Pull request by fcooper8472**
Second PR with the todos from https://github.com/pints-team/pints/pull/1091#issuecomment-608397671

### CODE REVIEW

**Comment by fcooper8472** [comment]
@martinjrobins @MichaelClerx it looks as though it might have to be the person who set up the appveyor integration who disables it.  Was it one of you two?

**Comment by MichaelClerx** [comment]
From the URL I'm guessing it was martin ;-)

https://ci.appveyor.com/project/martinjrobins/pints/

**Comment by fcooper8472** [comment]
> From the URL I'm guessing it was martin ;-)
> 
> https://ci.appveyor.com/project/martinjrobins/pints/

Ha!  Didn't see that!

**Comment by martinjrobins** [comment]
I've deleted the appveyor project

**Comment by fcooper8472** [comment]
@MichaelClerx please go ahead and merge if you're happy with these changes

**Pull request merged**
