### PR TITLE
1210 truncated normal

### PR DESCRIPTION
**Pull request by rcw5890**
Adds the truncated normal distribution as a prior, for #1210

### CODE REVIEW

**Review by ben18785 — APPROVED** [review]
@rcw5890 Great job -- a first for me but I have no critical feedback. Good to go for me!

**Comment by ben18785** [comment]
@MichaelClerx Can you have a look? I'm happy for this to go in.

**Review by MichaelClerx — COMMENTED** [review]
"Convert prior samples to be uniform within unit cube" --> Converting

**Comment by MichaelClerx** [comment]
Since the NormalLogPrior is deprecated in favour of Gaussian, should this be a TruncatedGaussianLogPrior ?

**Comment by MichaelClerx** [comment]
I remember @fcooper8472 did some work on ensuring the log priors behaved in a consistent and well-defined way at discontinuous boundary points, and were tested for that. Is this consistent with that work?

**Comment by fcooper8472** [comment]
Looks good to me!

**Comment by ben18785** [comment]
Happy with either truncated normal or truncated Gaussian (admit the last one is more consistent but I slightly regret deprecating the normal word -- this was my silly decision, I think).

**Comment by MichaelClerx** [comment]
We could merge it and open another ticket to discuss the naming? As long as it's fixed before the next release I'm happy.

Code looks great!

**Review by MichaelClerx — APPROVED** [review]

**Comment by rcw5890** [comment]
I just made two small changes: fixing that other heading in the log priors notebook, and adding a test for inputs at the bound.

**Review by ben18785 — APPROVED** [review]
@rcw5890 Looks great! Merging.

**Pull request merged**
