### PR TITLE
Restrict numpy multithreading when multiprocessing

### PR DESCRIPTION
**Pull request by MichaelClerx**
See #1356 

Current solution allows customisation of `ParallelEvaluator` class, but doesn't provide options for the `pints.evaluate` method or for controllers (which just use the new default)

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Seems `threadpoolctl` has no 2.7 support.

Also now noticing that numpy seeds are inherited by processes. This has never been a problem before as each worker gets a different task, but giving them all the same task now in functional testing, they are all returning the same result :D

**Comment by MichaelClerx** [comment]
Unit tests for this block indefinitely on ubuntu 16 (which is EOL since april, and will be removed from github actions in sept). Not sure why the tests block now...

**Comment by MichaelClerx** [comment]
Updated for Python 3 only now, and ready for review!

**Comment by MichaelClerx** [comment]
@tlestang I hear you had the same problem? Did you also solve it with threadpoolctl ?

**Review by DavAug — APPROVED** [review]
Thanks @MichaelClerx ! Looks convincing to me, but I am also not super familiar with the possible pitfalls of threading.

**Comment by MichaelClerx** [comment]
Thanks @DavAug !

**Pull request merged**
