### PR TITLE
Issue 653 controller multiuse exception

### LINKED ISSUE #653: Make controllers raise exception if used twice
Now that we've decided they're officially single use objects. See: #640

### PR DESCRIPTION
**Pull request by martinjrobins**
Fixes #653.

Raises a RuntimeException is the `run` method on a controller is called twice

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Cool! Do we need this for nested (and in the future ABC) too?

**Comment by martinjrobins** [comment]
> Cool! Do we need this for nested (and in the future ABC) too?

Yes, sorry forgot about the nested sampler controller....

**Comment by ben18785** [comment]
@MichaelClerx I've now added the nested sampler checks for multi-use of the controller. Are you happy with this to go in now?

**Review by MichaelClerx — APPROVED** [review]

**Comment by ben18785** [comment]
@MichaelClerx -- thanks!

**Pull request merged**
