### PR TITLE
Added a CHANGELOG.md file

### PR DESCRIPTION
**Pull request by MichaelClerx**
See #1202 

Anyone have any opinions on this?

Feel free to adapt/expand the current draft for whatever-comes-after-0.3.0 !

Would like to get this merged asap so that currently open PRs can start adding to it as well

### CODE REVIEW

**Review by martinjrobins — APPROVED** [review]
Thanks @MichaelClerx, changelog looks great. Perhaps have a link to the PR for each change, so the reader can get more info if they want?

**Comment by MichaelClerx** [comment]
> Thanks @MichaelClerx, changelog looks great. Perhaps have a link to the PR for each change, so the reader can get more info if they want?

Good idea, I've added that in!

**Comment by chonlei** [comment]
If the PR is what's needed in the CHANGELOG.md, maybe say that in the CONTRIBUTING.md?

**Review by rcw5890 — APPROVED** [review]
This looks good to me, I just made a tiny change to the changelog entry for #1183

**Comment by MichaelClerx** [comment]
> If the PR is what's needed in the CHANGELOG.md, maybe say that in the CONTRIBUTING.md?

Done!

**Comment by chonlei** [comment]
Should we add the transformation wrappers to it? Not really expecting users to use them directly, but it's there if they want...

**Comment by MichaelClerx** [comment]
Entirely up to you!

**Pull request merged**
