### PR TITLE
Issue#148 - emcee hammer mcmc

### PR DESCRIPTION
**Pull request by ben18785**
Need to import emcee in Travis build to stop it failing.

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Have fixed the import error and added a test: At the moment this method seems very slow, is that normal or am I using it wrong? @ben18785 ?

**Comment by MichaelClerx** [comment]
And are these walkers perhaps something we can parallelise?

**Comment by chonlei** [comment]
I am not sure if the emcee package has an inbuilt version of parallelisation of workers or not. But when I was trying it, I used the parallelisation code that we had in Pints to make things parallelised. So, yes, should be doable.

**Comment by MichaelClerx** [comment]
Thanks Chon! Ben just showed me that yes, it does have built-in parallelisation, so that's very good! We've made a ticket for it in fact :-)

**Comment by chonlei** [comment]
@MichaelClerx On that note, although they have builtin parallelisation, I remember I had some problems with their parallelisation -- so I adapted the one in Pints, maybe just something to watch out later.

**Pull request closed without merging**
