### PR TITLE
Renaming of normal -> gaussian throughout

### PR DESCRIPTION
**Pull request by ben18785**
All changes apart from flake8 implemented in s_convert_names.sh script.

Filename changes: all cases of 'normal' -> 'gaussian'

Within text changes:

- UnknownNoiseLogLikelihood -> GaussianLogLikelihood (I think by default we should assume sigma is unknown as it typically is)
- KnownNoiseLogLikelihood -> GaussianKnownSigmaLogLikelihood
- MultimodalNormalLogPDF -> MultimodalGaussianLogPDF
- NormalLogPDF -> GaussianLogPDF
- HighDimensionalNormalLogPDF -> HighDimensionalGaussianLogPDF
- MultivariateNormalLogPrior -> MultivariateGaussianLogPrior
- NormalLogPrior -> GaussianLogPrior
- Normal (in upper case so that it doesn't pull out any Scipy stuff by mistake) -> Gaussian wherever the word occurs
- multimodal_normal -> multimodal_gaussian
- high_dimensional_normal -> high_dimensional_gaussian
- normal_logpdf -> gaussian_logpdf
- '_normal ' -> '_gaussian '

Also changes MCMCSampling to MCMCController throughout PINTS.

Covers both #626 and #622

### CODE REVIEW

**Comment by ben18785** [comment]
@martinjrobins @MichaelClerx Whilst I see only a single test failing as a minor victory here, it'd be good if you could help me solve this issue...

**Comment by MichaelClerx** [comment]
Ok I'll have a look!

**Comment by ben18785** [comment]
Cool, have merged the other naming branch with this one since they are
similar issues.

**Comment by MichaelClerx** [comment]
@ben18785 what's happening? I was just trying to fix errors in this branch...

**Comment by MichaelClerx** [comment]
> Cool, have merged the other naming branch with this one since they are similar issues.

Oh ok. It's generally easier in the long run to handle separate topics in separate branches/PRs. You never know when somethings going to go wrong or create some unexpected issue and cause delays etc. Will try to merge in my changes and then re-check everything

**Comment by ben18785** [comment]
Ok, sorry, but reckon this one is easier to handle as one. Apologies for
hassle!

**Comment by ben18785** [comment]
@MichaelClerx Careful with some of these rechanges of normal -> Gaussian. Whenever we refer to a distribution, it should be Gaussian not normal.

**Comment by MichaelClerx** [comment]
Bit on the very next line we use the notation `N(0, sigma)` ?

**Comment by ben18785** [comment]
Yep, that's the mathematical notation that's used for Gaussians and normals
(I know a bit weird but think we need to be consistent with language).

**Comment by MichaelClerx** [comment]
OK, Think I've done everything except for renaming `Optimisation`.

Bit more involved than a find/replace in the end... adding aliases (with deprecation warnings) so all our projects using pints don't break, checking mentions in documentation, changing file and test names...

**Comment by ben18785** [comment]
@MichaelClerx Great! And thank you for this. Have made a note to include the studies in the overall regex find/replace for any future name changes.

**Comment by ben18785** [comment]
@martinjrobins Are you happy for us to merge this? Would be good to get this done to avoid future name conflicts...

**Comment by martinjrobins** [comment]
Sorry, I haven't had time to go though this in detail, but I'm happy for you to merge this (as long as @MichaelClerx is happy?)

**Comment by MichaelClerx** [comment]
We still need to think of a good name for the `Optimisation` class!

**Comment by ben18785** [comment]
I think we should go with OptimisationController to be the same as for sampling.

**Comment by MichaelClerx** [comment]
OK will get started on that now

**Pull request merged**
