### PR TITLE
Capturing pystan test output

### PR DESCRIPTION
**Pull request by MichaelClerx**
See #1305 

Makes the unit test output readable again.

~Although possibly harder to debug now if things go wrong.~
Have now made it so that it prints all if an error occurs

### CODE REVIEW

**Comment by MichaelClerx** [comment]
@ben18785 mind merging this before I make further changes?

**Comment by ben18785** [comment]
I've had a look and don't really understand what this all does: how about
you make one PR that fixes the output of the Stan file and tries to fix the
dictionary thing? Then perhaps on Tuesday you can explain it to me? Or we
get another person to review it as well as me further down the line?

**Comment by ben18785** [comment]
Or can chat through it now if you like? Whatever's easiest for you.

**Comment by MichaelClerx** [comment]
Usually we can catch printed output by redirecting python's `stdout` and `stderr` "streams" to some temporary string buffer. This is what the StreamCapture we already have in testing does.
But pystan compiles it's own C++ code, and when that prints it doesn't go through python's streams, so we need a different method to catch it. This is what the SubCapture class does, using some magic with file descriptors and stuff that I partially understood when I wrote it, and partially copied from a variety of tutorials.

So what happens in the pystan interface tests now is that a SubCapture is created before the operations that print to screen, and this catches all output. If there's an error I print that output to screen again, in case it helps in debugging. That's about it :D

**Comment by MichaelClerx** [comment]
The functional bits of the SubCapture code were copied from Myokit, btw, so it has been tested for a few years.

I've not added in any tests for it in pints as it's inside the `tests` directory, which is not tested. (We don't test the tests)

**Comment by MichaelClerx** [comment]
The only things I'm not too sure about are 

- whether the error handling code in the pystan test works - I should probably try this out?
- whether we should capture output in the test and leave it enabled by default, all 1000s of line, or whether we should move the SubCapture (and StreamCapture?) classes into pints main, add tests, and capture the pystan printed output all the time. This would stop it interfering with out controller log output, but could hide stuff from the user that stan devs didn't hide - maybe for a reason?

**Comment by MichaelClerx** [comment]
@fcooper8472 and @martinjrobins any thoughts on this? Code look ok? And should we suppress extension-module output only in the test, or do it in the main method?

**Comment by ben18785** [comment]
Thanks @MichaelClerx for the explanation. It sounds good to me! But, probs best to get feedback from a C++sy person rather than me!

**Comment by MichaelClerx** [comment]
It's this one @fcooper8472

**Comment by fcooper8472** [comment]
@MichaelClerx the code looks fine to me.  What I'm not clear on is why it would be in pints/tests?  It sure doesn't look like it's a test to me!

Is this functionality that you would expect someone to be able to use from PINTS?

**Comment by MichaelClerx** [comment]
Thanks @fcooper8472 , and good question too!

I can think of a couple of different ways to answer it

1. The `SubCapture` class is used only by tests, so goes with the other ThingsThatAreUsedByTestsButAreNotThemselvesTests in `tests/shared.py`.
2. There shouldn't be any ThingsThatAreUsedByTestsButAreNotThemselvesTests, instead these should be part of the (public or private) PINTS API, and have tests of their own
3. There might be some ThingsThatAreUsedByTestsButAreNotThemselvesTests, but this particular class should be part of the (public or private) PINTS API, so that it can be used inside the stan interface, and not by the test

I can be swayed either way in under a minute.

@ben18785 do you have a preference?

**Comment by MichaelClerx** [comment]
Discussed in meeting, easiest to leave it here for now and move later if needed

**Comment by fcooper8472** [comment]
Also discussed that @martinjrobins will take a quick look.  But I'm happy with it.

**Comment by MichaelClerx** [comment]
Thanks Fergus!

**Comment by MichaelClerx** [comment]
One thing I've taken from @martinjrobins experience is that we should slap a label on the class saying it's not thread safe.
Unless we can make `_start_capturing` atomic somehow? But again, easiest route is to slap a warning on and not worry 😅

**Review by martinjrobins — CHANGES_REQUESTED** [review]
this looks in general great @MichaelClerx. As I mentioned in the meeting, my main worry is that there might be different instances of `SubCapture`, maybe on different threads, both calling `_start_capturing` and `_stop_capturing`. You are currently assuming that `_stop_capturing` is always called after `_start_capturing`. Can you use a `Lock` (https://docs.python.org/3/library/threading.html#threading.Lock.acquire) to make sure that only one `SubCapture` is between `_start_capturing` and `_stop_capturing` at a time? And can you do the same in myokit :)

**Comment by martinjrobins** [comment]
> One thing I've taken from @martinjrobins experience is that we should slap a label on the class saying it's not thread safe.
> Unless we can make `_start_capturing` atomic somehow? But again, easiest route is to slap a warning on and not worry

I'd be happy with a not thread safe warning as well :)

**Review by martinjrobins — APPROVED** [review]
great, happy with that

**Pull request merged**
