### PR TITLE
Documentation (and naming?) changes in pints.diagnostics: redux

### PR DESCRIPTION
**Pull request by ben18785**
See #1101 

- [x] Update docstring for autocorrelate_negative: I don't understand what it does?
- [x] Deprecate ess_single_param in favour of effective_sample_size_single_parameter, as we don't use "param" anywhere else in PINTS names, and the next method in the same file is called effective sample size ?
- [x] Haven't made effective_sample_size_single_parameter private as I can imagine wanting to use it

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Thanks @ben18785 !

```
>>> def _autocorrelate_negative(autocorrelation):
...     T = 1
...     for a in autocorrelation:
...         if a < 0:
...             return T - 1
...         T += 1
...     return T
... 
>>> _autocorrelate_negative([0, 1, 2, 3, 4, 5, 6])
8
>>> _autocorrelate_negative([0, 1, 2, 3, 4, -5, -6])
5
```

I'm thinking the 8 should be a 7? Have updated code & docstring accordingly

**Comment by MichaelClerx** [comment]
```
def _autocorrelate_negative(autocorrelation):
    """
    Returns the index of the first negative entry in ``autocorrelation``, or
    ``len(autocorrelation)`` if no negative entry is found.
    """
    try:
        return np.where(np.asarray(autocorrelation) < 0)[0][0]
    except IndexError:
        return len(autocorrelation)

>>> _autocorrelate_negative([0, 1, 2, 3, 4, 5, 6])
7
>>> _autocorrelate_negative([0, 1, 2, 3, 4, -5, -6])
5
```

- less readable
+ faster

**Comment by ben18785** [comment]
Great: no need for it to be readable so long as it does what it needs to do.

**Review by MichaelClerx — APPROVED** [review]

**Comment by MichaelClerx** [comment]
THanks @ben18785 !

**Pull request merged**
