### PR TITLE
Fixed annulus notebook

### PR DESCRIPTION
**Pull request by MichaelClerx**
Was using deprecated/removed matplotlib syntax for 3d plots.

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Link to the actual differences: https://github.com/pints-team/pints/pull/1472/files#diff-a7d2aac41dfbe01183010d229bc51a6a8257603d748a9392ab161862fd846c5eL379-L385  (click "Load diff", then look at highlighted lines)

So replaced

```
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
ax = fig.gca(projection='3d')
ax.plot(stacked[:, 0], stacked[:, 1], stacked[:, 2], '.', alpha=0.1)
ax.legend()

plt.show()
```
by
```
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.plot(stacked[:, 0], stacked[:, 1], stacked[:, 2], '.', alpha=0.1)
plt.show()
```

- import doesn't seem to be needed anymore
- fig.gca no longer has a `projection` keyword
- remove legend command that didn't do anything (and raised a warning to tell us)

**Comment by MichaelClerx** [comment]
@chonlei @martinjrobins @DavAug @rccreswell ?

**Comment by MichaelClerx** [comment]
Great. Now 3.11 is making the stan and nuts tests fall over

**Review by DavAug — APPROVED** [review]
Thanks @MichaelClerx for fixing this. Sorry for taking so long with the review

**Comment by MichaelClerx** [comment]
Woohoo! Thanks @DavAug . The tests were failing until this afternoon, so perfectly valid excuse to not review :D :D :D

**Pull request merged**
