### PR TITLE
Optimisers: best vs guessed position

### PR DESCRIPTION
**Pull request by MichaelClerx**
See #1411

Changes:

- The pints.Optimiser interface now has methods x_best, f_best, x_guessed, and f_guessed (replacing the old methods xbest and fbest)
- By default the `_guessed` methods just call `_best`
- But the ES methods return the mean of their proposal distribution
- The controller still uses `_best` by default, but this can be adjusted with `set_f_guessed_tracking`
- In a future PR, the controller should start using `_guessed` by default

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Uncovered an issue in xNES, and probably SNES (and PSO?) to do with the triangle transform used to check rectangular boundaries: see #25

As a result, have kept the strategy on f_best for now. Will need to address this in future PRs.

**Comment by MichaelClerx** [comment]
The notebooks are not substantially changed except for `ask-and-tell.ipynb`, which now includes some visualisations of the difference between the best and guessed value.

**Review by DavAug — COMMENTED** [review]
Thanks @MichaelClerx ! Very useful to be able to distinguish between the best seen and best guess location.

Just checking: If CMAES previously returned its best guess as 'fbest' and we now change to returning 'f_best' is this a desired change in the algorithm (even if it's only temporary and planned to be changed in a future PR)?

**Comment by MichaelClerx** [comment]
> Just checking: If CMAES previously returned its best guess as 'fbest' and we now change to returning 'f_best' is this a desired change in the algorithm (even if it's only temporary and planned to be changed in a future PR)?

The way we had implemented it, the `fbest` returned was the best seen, not the best guessed. This is probably not desirable, as it can lead to situations like this one:

local-map-zoom-xbest

Here the orange circle is the returned x_best (best seen), but the blue crosses show that the method has converged to a different point (x_guessed)

**Comment by MichaelClerx** [comment]
So I really want to set it to returning the best guessed point instead. But at the moment that just exposes a bug in xnes and makes lots of tests fail, so I want to fix that first 😓😓😓

**Comment by DavAug** [comment]
> > Just checking: If CMAES previously returned its best guess as 'fbest' and we now change to returning 'f_best' is this a desired change in the algorithm (even if it's only temporary and planned to be changed in a future PR)?
> 
> The way we had implemented it, the `fbest` returned was the best seen, not the best guessed. This is probably not desirable, as it can lead to situations like this one:
> 
> local-map-zoom-xbest
> 
> Here the orange circle is the returned x_best (best seen), but the blue crosses show the requested points, from which you can see that the method has converged to an x_guessed != x_best_seen

That is very interesting! So just to clarify: the black points are the actual steps taken by CMAES and the blue crosses are the samples points to estimate the gradient? Or are the blue crosses really just guesses and if so, why are there more guesses than steps?

**Comment by MichaelClerx** [comment]
> That is very interesting! So just to clarify: the black points are the actual steps taken by CMAES and the blue crosses are the sampled points which are used to estimate the gradient? Or are the blue crosses really just guesses and if so, why are there more guesses than steps?

Sorry I didn't explain that well did I :D 
The black dots are the successive "best seen" points, so the ones you obtain if you call x_best() at each iteration. The blue crosses meanwhile are the evaluated points. The mean of the proposal distribution isn't plotted here, but you can see that it doesn't overlap with the black dots. And at the end of the optimisation the proposal distribution is centered in the area with very dense blue crosses. So that's where CMAES thinks the optimum is, and where its putting all its effort. But this is not the point we are returning at the moment.

There are more examples of this in the updated ask-and-tell.ipynb notebook. Only in these problems (and I suspect in most problems we've looked at) the proposal distribution does end up converging to the best-seen score.

**Comment by DavAug** [comment]
> > That is very interesting! So just to clarify: the black points are the actual steps taken by CMAES and the blue crosses are the sampled points which are used to estimate the gradient? Or are the blue crosses really just guesses and if so, why are there more guesses than steps?
> 
> Sorry I didn't explain that well did I :D
> 
> The black dots are the successive "best seen" points, so the ones you obtain if you call x_best() at each iteration (although this point stays the same for several iterations at a time, unlike the mean of the proposal distribution, which bounces around a lot).
> 
> The blue crosses meanwhile are the evaluated points.
> 
> The mean of the proposal distribution isn't plotted here, but you can see where it ends up because all the blue crosses converge to a single area. So that (x_guessed) is where CMAES thinks the optimum is, and where its putting all its effort. But this is not the point we are returning at the moment (x_best).
> 
> There are more examples of this in the updated ask-and-tell.ipynb notebook. Only in these problems (and I suspect in most problems we've looked at) the proposal distribution does end up converging to the best-seen score.

Is it possible at all that the in this example the CMAES algorithm decides that it has converged based on the evaluated points, but doesn't updated updated the final 'xbest', and we return the penultimate 'xbest'? I just find it suspicious that the steps never get close to the evaluated points.

**Review by DavAug — APPROVED** [review]

**Comment by MichaelClerx** [comment]
Good question, I'll try and do a plot of both points

**Pull request merged**
