### PR TITLE
Added an example of combining opt. and mcmc, and optimising on a loglikelihood

### PR DESCRIPTION
**Pull request by MichaelClerx**
See #159.

### CODE REVIEW

**Comment by MichaelClerx** [comment]
@martinjrobins ?

**Comment by MichaelClerx** [comment]
Fair point. Have added a new example and updated the old one

**Comment by MichaelClerx** [comment]
We should also remember to keep the index in `examples/README` up to date!

**Comment by MichaelClerx** [comment]
@martinjrobins care to have another look?

**Comment by MichaelClerx** [comment]
@ben18785 could you have a quick peek at this?

**Comment by ben18785** [comment]
Could we hold back on this — sorry been meaning to comment on it. Not sure the example here is great, to be honest...

**Pull request merged**
