### PR TITLE
Mcmc plot examples

### PR DESCRIPTION
**Pull request by chonlei**
see e.g. #63 #66

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Current plots:
- https://github.com/pints-team/pints/blob/mcmc-plot-examples/examples/plot-mcmc-autocorrelation-plot.ipynb
- https://github.com/pints-team/pints/blob/mcmc-plot-examples/examples/plot-mcmc-pairwise-scatterplots.ipynb
- https://github.com/pints-team/pints/blob/mcmc-plot-examples/examples/plot-mcmc-predicted-time-series.ipynb
- https://github.com/pints-team/pints/blob/mcmc-plot-examples/examples/plot-mcmc-trace-plots.ipynb

**Comment by chonlei** [comment]
Working on https://github.com/pints-team/pints/blob/mcmc-plot-examples/examples/plot-mcmc-pairwise-scatterplots.ipynb, I will push it once I am done!

**Comment by chonlei** [comment]
We could probably include that plot_kde_1d(), plot_kde_2d() etc or even the whole plot in https://github.com/pints-team/pints/blob/mcmc-plot-examples/examples/plot-mcmc-pairwise-scatterplots.ipynb as part of Pints? Or just leave them as examples? 

Not many people like doing those for loops every time when they test something, I think would be nice to have a function to quickly plot those for them. If later on they really want nicer ones, they can go and plot it again, but probably nice to provide them a shorthand for this?

**Comment by chonlei** [comment]
Created a clean history version (with only the 4 example plots added) as another PR, see #88. 

Close down this PR after the other is approved.

**Pull request closed without merging**
