### PR TITLE
PopulationMCMC: Tempering and Mixing

### LINKED ISSUE #409: Set temperature schedule on population MCMC to be uniform on log scale
As per SMC (and per Radford Neal's AIS article on p10: ftp://www.cs.toronto.edu/pub/radford/ais-rev.pdf)

### PR DESCRIPTION
**Pull request by MichaelClerx**
Fixes #409

### CODE REVIEW

**Comment by MichaelClerx** [comment]
@sanmitraghosh was just asking about the form ```P(theta|y)^t P(theta)^(1-t)```. Is that appropriate here?

**Comment by MichaelClerx** [comment]
Seems to be failing style but otherwise fine!

@ben18785 If you can have a look and see if it's otherwise ready we can merge this in!

**Comment by MichaelClerx** [comment]
@ben is this related to #487  too?

**Comment by MichaelClerx** [comment]
@ben18785 do you know the status of this?

**Comment by MichaelClerx** [comment]
Have fixed the mess I made of this branch with `git`. Please delete your local copy and re-checkout the branch before continuing work on this.

**Comment by MichaelClerx** [comment]
Not any changes made in here should be re-applied on top of #1246

**Comment by ben18785** [comment]
I think this approach probably needs reimplementing in a fresh branch (and possibly needs testing vs a linear temperature schedule), so closing for now.

**Pull request closed without merging**
