### PR TITLE
Update link to source in Haario Bardenet ACMC

### PR DESCRIPTION
**Pull request by FelixNoessler**
doi.org was missing in the link to a source

### CODE REVIEW

**Review by MichaelClerx — APPROVED** [review]
Thanks @FelixNoessler !

**Comment by MichaelClerx** [comment]
@FelixNoessler if you can update the main branch this was based on all the tests should work & I can merge it in

**Comment by FelixNoessler** [comment]
Hello, I updated the branch. Let me know if it didn't work.

**Comment by MichaelClerx** [comment]
Thanks @FelixNoessler ! Welcome to the team

**Pull request merged**
