### PR TITLE
Testing Python3.9 testing

### PR DESCRIPTION
**Pull request by MichaelClerx**
See #1242

### CODE REVIEW

**Comment by fcooper8472** [comment]
This looks fine.

We should also retire testing for 3.5, which has reached end of life.  New ticket for that, or just add it to this change?

**Comment by MichaelClerx** [comment]
Can we wait for it to break? I'm sure there's still voluntary and involuntary 3.5 users out there in the academic ecosystem

**Comment by fcooper8472** [comment]
Yeah, that's definitely something that we can do.  And that might be appropriate, if there are still systems out there without access to 3.6.

The opportunity cost is not getting to use new features such as f-strings, which will make PINTS code nicer.  Not a huge deal, though.

Why did we drop 3.4?

**Comment by MichaelClerx** [comment]
Good question!

We're still testing 2.7 so f strings are out anyway. But 3.4... I think we just couldn't be bothered to wait for more than 4 unit tests? Maybe we should add it back in now, since the github actions thing seems to be working fairly quickly?

**Comment by MichaelClerx** [comment]
> Error: Version 3.4 with arch x64 not found

Maybe that was why :D

**Comment by MichaelClerx** [comment]
Psssst @fcooper8472 !

**Review by fcooper8472 — APPROVED** [review]
Looks good to me!

**Comment by MichaelClerx** [comment]
Thanks!

**Pull request merged**
