### PR TITLE
I253 standard metropolis

### PR DESCRIPTION
**Pull request by chonlei**
Add standard Metropolis Hasting, see #253 

This is Metropolis Random Walker ( i.e. just stripping the adaptive covariance from the AdaptiveCovarianceMCMC in #253 ) than generalised Metropolis Hasting as mentioned here #209

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Hi Chon! Is it metropolis or metropolis Hastings you've done?

**Comment by chonlei** [comment]
Hi Michael! I removed the adaptive covariance part of the AdaptiveCovarianceMCMC you have mentioned in #253. I am not sure what is Metropolis. I thought it is usually known as Metropolis random walker with normal step.

**Comment by MichaelClerx** [comment]
Have a look at the stuff Ben wrote in the tickets about this then! Plus wiki
etc. :) It's to do with how you choose the next points to test!



On Sat, 24 Feb 2018 04:49:54 -0800 Chon Lok Lei <notifications@github.com>
wrote

**Comment by chonlei** [comment]
@MichaelClerx I had a thought about it, and added a comment about adding asymmetric proposal steps [which have not been done]. But then that requires an input of a function that we can sample from. If that is what we want, then I will try adding that flexibility to the class! (As currently we are only using Normal proposal step -- so "Random walker".) :)

I am not sure about the log transform, how and why we want to do that. @ben18785 I thought we only wanted to have that extra flexibility for users to use any kind of proposal step distribution (either symmetric like Random walker or asymmetric). Please correct me if I am wrong! :)

**Comment by MichaelClerx** [comment]
No need to implement extra things! Just make sure you give it the right name!

n Sat, 24 Feb 2018 06:12:09 -0800 Chon Lok Lei <notifications@github.com> wrote

**Comment by chonlei** [comment]
Ah, I see what you mean now. Okay! Will do!

**Comment by MichaelClerx** [comment]
Thanks @chonlei looks great except for this bit:

    # Choose a covariance matrix for the proposal step
    # This will be the diagonose of the covariance matrix
    sigma0 = np.abs(real_parameters) * 0.000005

Looking at the results, maybe it'd be easier to use a KnownNoiseLogLikelihood in this example? Then we should be able to find a nicer guess for sigma0 perhaps?

**Pull request merged**
