### PR TITLE
i104 HMC

### PR DESCRIPTION
**Pull request by MichaelClerx**
See #104

### CODE REVIEW

**Comment by ben18785** [comment]
@sanmitraghosh Do we have sensitivities in Pints yet?

**Comment by sanmitraghosh** [comment]
@ben18785  Yes, @MichaelClerx  has got a nice implementation with "@method_s1"

**Comment by ben18785** [comment]
Ok, great. So there's nothing stopping me from finishing HMC then?

**Comment by MichaelClerx** [comment]
Nope!

**Comment by sanmitraghosh** [comment]
You might have to implement sens for normal priors. But otherwise you can start HMC

**Comment by MichaelClerx** [comment]
This looks quite good already! Let me know if I can help @ben18785 !

**Pull request closed without merging**
